# Generated by Django 5.0.1 on 2024-01-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Too bad'), (5, 'Excellent'), (4, 'Good'), (3, 'Normal'), (2, 'Bad')]),
        ),
    ]
