# Generated by Django 5.0.1 on 2024-01-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Excellent'), (1, 'Too bad'), (4, 'Good'), (2, 'Bad'), (3, 'Normal')]),
        ),
    ]
